categories = ["悟", "计算机", "金融"]

[page.comment.giscus]
  enable = true
  repo = "arrebole/arrebole.github.io"
  repoId = "MDEwOlJlcG9zaXRvcnkzNjQ2MTU2NDQ="
  category = "Announcements"
  categoryId = "DIC_kwDOFbuX3M4CgPTT"
  lang = "zh-CN"
