baseURL = 'https://arrebole.github.io'
languageCode = 'zh-cn'
title = "Arrebole's Blog"

[params]
  categories = ["修行", "编程", "游戏"] 

[markup]
  [markup.highlight]
    lineNumbersInTable = true
    noclasses = false
    tabWidth = 2
